
pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud_serv_conx'
    organization: 'talfaro-bcn'
    projectKey: 'talfaro-bcn_pet-clinic'
    projectName: 'pet-clinic'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false

- task: dependency-check-build-task@6
  inputs:
    projectName: 'pet-clinic'
    scanPath: '$(Build.SourcesDirectory)/build/libs'
    format: 'HTML'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'docker1_srv'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'docker1_srv'
    repository: 'talfaro-bcn/pet-clinic'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: |
    sudo apt-get install -y rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
    sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
    trivy image talfaro-bcn/pet-clinic:latest
  displayName: Image Scan

- task: Docker@2
  inputs:
    containerRegistry: 'docker1_srv'
    repository: 'talfaro-bcn/pet-clinic'
    command: 'push'
    tags: 'latest'